### ISSUE TITLE
mass reservations should not be cleared when file is not available

### ISSUE THREAD

**Issue by ChristianBeer** [MersenneForum/MersenneForumAliquot#8]
This is from a recent yafu shutdown where the URL is not available. Code at the time was at aebc7f672eb230cbacc54e4de32c2609eb33c401

The default action should be to retain the current reservations not drop them.

```
ERROR:mfaliquot:URLError: <urlopen error [Errno 110] Connection timed out>
Traceback (most recent call last):
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aliquot/MersenneForumAliquot/mfaliquot/__init__.py", line 38, in blogotubes
    page = request.urlopen(req, data).read().decode(encoding)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/opt/rh/rh-python36/root/usr/lib64/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
ERROR:mfaliquot.application.reservations:unable to get mass reservation file for yafu@home
INFO:mfaliquot.application.reservations:mass reservee yafu@home: add 0 seqs, drop 4528
```

**Comment by dubslow** [comment]
Was this not fixed (as well as multiple other very similar bugs) by 49ab3fa6770af333e54288363598fb0c2697b25?
